[theme]
primaryColor = "#2c3e50"  # Dark blue for main accents (trustworthy and professional)
backgroundColor = "#E0F7FA"  # Light blue as a fallback color if CSS fails
secondaryBackgroundColor = "#E0E0E0"
textColor = "#000000" 
font = "serif"  # Serif font for a more academic feel
